# Copyright (C) 2026 CO2 Saver contributors
# SPDX-License-Identifier: GPL-3.0-only

"""Home Assistant-independent accounting domain for CO2 Saver."""

from .accounting import (
    calculate_direct_emissions,
    decompose_flows,
    normalize_interval,
    transport_lower_bound,
)
from .errors import (
    DomainInvariantError,
    DomainValidationError,
    IntervalRejectionReason,
    StorageRejectionReason,
)
from .models import (
    ConsumerEmissionView,
    ConsumerFlow,
    ConsumerLoad,
    ConsumerLoads,
    ConsumerShare,
    ConsumptionMode,
    DirectEmissionFactors,
    EmissionBreakdown,
    EnergySink,
    EnergySource,
    FlowDecomposition,
    GuaranteedFlow,
    InputTopology,
    IntervalEmissionResult,
    IntervalWindow,
    InverterIntervalInput,
    MarginRemainder,
    NormalizedInterval,
    RejectedInterval,
    SmartMeterIntervalInput,
    loads_from_meters,
    loads_from_shares,
)
from .quantities import (
    EmissionDensity,
    EmissionFactor,
    Emissions,
    Energy,
    ExactInput,
    Ratio,
    exact_fraction,
)
from .storage import (
    ConsumerStorageCredit,
    StorageEffects,
    StorageLedger,
    StorageRejected,
    StorageTransition,
    advance_storage,
)

__all__ = (
    "ConsumerEmissionView",
    "ConsumerFlow",
    "ConsumerLoad",
    "ConsumerLoads",
    "ConsumerShare",
    "ConsumerStorageCredit",
    "ConsumptionMode",
    "DirectEmissionFactors",
    "DomainInvariantError",
    "DomainValidationError",
    "EmissionBreakdown",
    "EmissionDensity",
    "EmissionFactor",
    "Emissions",
    "Energy",
    "EnergySink",
    "EnergySource",
    "ExactInput",
    "FlowDecomposition",
    "GuaranteedFlow",
    "InputTopology",
    "IntervalEmissionResult",
    "IntervalRejectionReason",
    "IntervalWindow",
    "InverterIntervalInput",
    "MarginRemainder",
    "NormalizedInterval",
    "Ratio",
    "RejectedInterval",
    "SmartMeterIntervalInput",
    "StorageEffects",
    "StorageLedger",
    "StorageRejected",
    "StorageRejectionReason",
    "StorageTransition",
    "advance_storage",
    "calculate_direct_emissions",
    "decompose_flows",
    "exact_fraction",
    "loads_from_meters",
    "loads_from_shares",
    "normalize_interval",
    "transport_lower_bound",
)
